### ISSUE TITLE
Frontend Glow

### ISSUE THREAD

**Issue by npereznyc** [jordbort/project-3-fitness-frontend#56]
- Feature Name: Displaying username on each post
- Intended behavior: To display each user’s username at the top of each of their posts.
- Current Behavior: Working as intended!
- Code Snippet:
```
const [users, setUsers] = useState([])

const findUsernameByOwner = (owner) => {
    for (let i = 0; i < users.length; i++) {
        if (owner === users[i]._id) {
            return users[i].username
        }
    }
}
```
- Contextual notes and insights about design decision: We felt it was important for the functionality of the app to see who posted each post.

**Comment by becomingaria** [comment]
Overall the site is pretty fleshed out. I was very impressed by the sign-in page that it hid my password as I typed. The feeling of logging in and posting within the application was very satisfying and it looks professional.
