### ISSUE TITLE
Frontend Grow

### ISSUE THREAD

**Issue by npereznyc** [jordbort/project-3-fitness-frontend#57]
- Feature Name: Header & Profile button when viewing another profile
- Intended Behavior: When you click on your profile name or on the profile button, you should be taken to your profile page (this works on all pages except when you’re looking at someone else’s profile).
- Current Behavior: When you’re looking at someone else’s profile, you’re currently unable to change directly to another profile. The links don't work.
- Code Snippet:
```
<div className="header">
    <Link to="/about"><h1>FitCheck</h1></Link>
    {currentUserName ? <Link to={"/profile/" + currentUserID}><p>Logged in: <span className='logged-in'>{currentUserName}</span></p></Link> : <Link to="/login/"><p><span className='not-logged-in'>Not logged in</span></p></Link>}
    {/* Why does this link not change pages if you're looking at another user's profile? */}
</div>
```
- Contextual notes and insights about design decision: We'd like to get this functionality working because it’s not a great user experience to not be able to switch between profiles.

**Comment by becomingaria** [comment]
The profile links were something that stood out to me while reviewing the site as a user. In addition to the grows you've mentioned, I'd take a look at the CSS for the user to determine what is and isn't clickable in the application (possibly with a hover effect) so the user knows what text is designed to be clickable.

**Comment by jordbort** [comment]
Links to profile page have been fixed, and links now turn blue when hovered over.
